### ISSUE TITLE
Generate 10-Digit Registration Codes API

### ISSUE THREAD

**Issue by sendistephen** [sendistephen/dfcu-hr-manager#2]
As an Admin, I need an API to generate unique 10-digit registration codes that I can distribute to new employees for their registration process.

#### Endpoint Details:

- URL: /api/admin/generate-code
- Method: POST
- Authentication: Admin-only access via NextAuth.

### Functionality:

- Generate a unique 10-digit alphanumeric code.
- Ensure the code is unique across the system.
- Store the generated code in the database with metadata

- Response:
   Success (201 Created):
```
{
  "message": "Registration code generated successfully.",
  "code": "ABC1234567",
  "statusCode": 201
}
```

- Error Responses:
   `401 Unauthorized` – If the requester is not an authenticated admin.
   `500 Internal Server Error` – For unexpected failures.

- Security Measures:
   Prevent brute-force attempts to guess registration codes.

### Tasks:

- [ ] Create RegistrationCode Model:
        Ensure the RegistrationCode model includes code, issuedBy, isUsed, createdAt, and expiresAt.

- [ ] Develop Generate Code API:
        Implement the `/api/admin/generate-code` endpoint.
        Generate unique 10-digit alphanumeric codes.
        Save the code with relevant metadata in the database.
        Implement Uniqueness Check:
        Ensure generated codes do not duplicate existing codes.

- [ ] Write Unit Tests:
        Test code generation for uniqueness.
        Test proper storage of registration codes.

- [ ] Document API with Swagger:
       Add Swagger documentation for the /api/admin/generate-code endpoint.

#### Definition of Done:

- Admin can generate unique 10-digit registration codes via the API.
- Generated codes are stored with correct metadata.
- The API is protected against unauthorized access and brute-force attacks.
- All unit tests pass, ensuring code uniqueness and correct storage.
- The generate code API is fully documented in Swagger.
