### ISSUE TITLE
Retrieve Registration Codes API

### ISSUE THREAD

**Issue by sendistephen** [sendistephen/dfcu-hr-manager#3]
As an Admin, I need an API to retrieve all generated registration codes, including their usage status and expiration details, to manage and monitor the registration process effectively.

#### Endpoint Details:

- URL: /api/admin/registration-codes
- Method: GET
- Authentication: Admin-only access via NextAuth.

#### Functionality:
Retrieve a list of all registration codes issuedBy (Admin ID)

- Response: Success (200 OK):
```
{
  "registrationCodes": [
    {
      "code": "ABC1234567",
      "issuedBy": "adminId123",
      "isUsed": false,
      "createdAt": "2024-04-27T12:34:56.789Z",
      "expiresAt": "2024-04-28T12:34:56.789Z"
    },
    // More codes...
  ],
  "statusCode": 200
}
```

- Error Responses:

- `401 Unauthorized` – If the requester is not an authenticated admin.
- `500 Internal Server Error` – For unexpected failures.

- Testing: Write unit tests to verify data retrieval and access restrictions.

- Documentation: Document the API endpoint using Swagger with request and response schemas.

#### Tasks:

- [ ] Develop Retrieve Codes API: Implement the /api/admin/registration-codes endpoint.
- [ ] Fetch all registration codes from the database.
- [ ] Write Unit Tests: Test retrieval of all codes.
- [ ] Document API with Swagger: Add Swagger documentation for the /api/admin/registration-codes endpoint.
       
### Definition of Done:

- Admin can retrieve all registration codes with accurate details via the API.
- The API is protected against unauthorized access.
- All unit tests pass, ensuring correct data retrieval and access control.
- The retrieve codes API is fully documented in Swagger.
