### ISSUE TITLE
Develop API Endpoint for Updating Employee Details

### ISSUE THREAD

**Issue by sendistephen** [sendistephen/dfcu-hr-manager#5]
As an Admin, I need an API to update employee information such as Date of Birth and ID Photo, ensuring that the employee records remain accurate and up-to-date.

#### Endpoint Details:

- URL: /api/admin/employees/:employeeNumber
- Method: PUT
- Authentication: Admin-only access via NextAuth.

#### Functionality:

- Allow admins to update the following employee fields:
- `dateOfBirth`: Date (ISO 8601 format)
- `photoId`: Image file (Base64-encoded)

- Request Body:

```
{
  "dateOfBirth": "1990-01-01",
  "photoId": "base64string"
}
```

- Response:Success (200 OK):

```
{
  "message": "Employee details updated successfully.",
  "employee": {
    "employeeNumber": "EMP0001",
    "surname": "Doe",
    "otherNames": "John",
    "dateOfBirth": "1990-01-01",
    "photoId": "base64string",
    "registrationCode": "ABC1234567",
    "createdAt": "2024-04-27T12:34:56.789Z",
    "updatedAt": "2024-04-28T10:20:30.456Z"
  },
}
```
##### Error Responses:

- `401 Unauthorized` – If the requester is not an authenticated admin.
- `404 Not Found` – If the employee does not exist.
- `400 Bad Request` – If the input data is invalid.
- `500 Internal Server Error` – For unexpected failures.
- Write unit tests to verify update functionality and access restrictions.
- Document the API endpoint using Swagger with request and response schemas.

### Tasks:

- [ ] Implement the `/api/admin/employees/:employeeNumber` endpoint.
- [ ] Allow updates to dateOfBirth and idPhoto.
- [ ] Validate the format of dateOfBirth.
- [ ] Validate and handle the idPhoto input.
- [ ] Test successful updates with valid data.
- [ ] Test updates with invalid data formats.
- [ ] Test updates on non-existent employees.
- [ ] Test access restrictions for unauthorized users.
- [ ] Add Swagger documentation for the `/api/admin/employees/:employeeNumber` endpoint.

### Definition of Done:

- Admin can update employee details via the API.
- The API is protected against unauthorized access.
- All unit tests pass, ensuring correct update functionality and access control.
- The staff update API is fully documented in Swagger.
