### ISSUE TITLE
Develop API Endpoint to Retrieve API Performance Metrics

### ISSUE THREAD

**Issue by sendistephen** [sendistephen/dfcu-hr-manager#7]
As an Admin, I need an API to view performance metrics of the system's APIs, including the number of requests, successful responses, failed responses, and average response times, to monitor and ensure the system's reliability and efficiency.

#### Endpoint Details:

- URL: `/api/admin/performance-metrics`
- Method: `GET`
- Authentication: Admin-only access via NextAuth.

#### Functionality:

- Collect and return metrics such as:
   - Total Requests: Total number of API calls made.
   - Successful Requests: Number and percentage of successful responses.
   - Failed Requests: Number and percentage of failed responses.
   - Average Response Time: Mean time taken to process requests.
   - Request Trends: Metrics over specific time intervals (e.g., last 24 hours).

##### Response:`Success (200 OK)`:
```
{
  "metrics": {
    "totalRequests": 1500,
    "successfulRequests": 1450,
    "failedRequests": 50,
    "successRate": "96.67%",
    "failureRate": "3.33%",
    "averageResponseTimeMs": 250,
    "requestTrends": [
      {
        "time": "2024-04-27T12:00:00Z",
        "requests": 100
      },
      // More trend data...
    ]
  },
  "statusCode": 200
}
```
##### Error Responses:

- `401 Unauthorized` – If the requester is not an authenticated admin.
- `500 Internal Server Error` – For unexpected failures.
- Write unit tests to verify accurate metric collection and reporting.
- Document the API endpoint using Swagger with request and response schemas.

### Tasks:

- [ ] Integrate middleware or use a monitoring tool to track API performance metrics.
- [ ] Implement the /api/admin/performance-metrics endpoint.
- [ ] Aggregate and return the collected metrics.
- [ ] Test accurate collection and retrieval of metrics.
- [ ] Test access restrictions for unauthorized users.
- [ ] Add Swagger documentation for the /api/admin/performance-metrics endpoint.

### Definition of Done:

- Admin can retrieve comprehensive API performance metrics via the API.
- The API is protected against unauthorized access.
- All unit tests pass, ensuring accurate metric collection and access control.
- The performance metrics API is fully documented in Swagger.
